services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    healthcheck:
      test: ["CMD-SHELL", "sleep 20"]
      interval: 1s                    
      timeout: 21s                     
      retries: 1     
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic

  scrapper:
    build: ./scrapper
    container_name: scrapper
    depends_on:
      es01:
        condition: service_healthy
    networks:
      - elastic
    environment:
      ELASTIC_URL: "http://es01:9200"
      ELASTIC_USER: "elastic"
      ELASTIC_PASS: "changeme"

  db:
    build: ./Elastic
    container_name: db
    depends_on:
      es01:
        condition: service_healthy
    networks:
      - elastic
    ports:
      - "8080:8080"
    environment:
      ELASTIC_URL: "http://es01:9200"
      ELASTIC_USER: "elastic"
      ELASTIC_PASS: "changeme"
  
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - elastic
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no", "--maxmemory", "50mb", "--maxmemory-policy", "allkeys-lru"]

  hadoop-analytics:
    build:
      context: ./hadoop
      dockerfile: Dockerfile
    container_name: hadoop-analytics
    volumes:
      - ./hadoop:/pig/data
      - ./hadoop/results:/pig/results
    depends_on:
      es01:
        condition: service_healthy
    environment:
      - JAVA_HOME=/usr/local/openjdk-8
    networks:
      - elastic
    profiles:
      - analytics

networks:
  elastic:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

volumes:
  esdata:
    driver: local
