services:
  pig-processor:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./results:/pig/results
      - .:/pig/data
    command: ["/bin/bash", "-c", "chmod +x /pig/data/*.sh && rm -rf /pig/data/clean_new && rm -rf /pig/results/* && pig -x local /pig/data/pig_scripts/filter_data.pig && /pig/data/export_events.sh && pig -x local /pig/data/pig_scripts/process_events.pig"]
    restart: "no"

volumes:
  pig-results:
    driver: local